name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "TRUE"
          SHOW_PROFILE_VIEWS: "FALSE"
          SHOW_LOC_CHART: "FALSE"
          SHOW_PROJECTS: "FALSE"
          SHOW_COMMIT: "FALSE"
          SHOW_DAYS_OF_WEEK: "FALSE"
          SHOW_LANGUAGE: "FALSE"
          SHOW_EDITORS: "FALSE"
          SHOW_TIMEZONE: "FALSE"
          SHOW_OS: "FALSE"
          SHOW_SHORT_INFO: "FALSE"
          SYMBOL_VERSION: 2
